# Change these first
owner: saxobroko # Your GitHub username
repo: SaxoMaintenance # Your Github repository name

# Add your sites here
sites:
  - name: Home
    url: https://saxobroko.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.saxobroko.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://cdn.statically.io/img/saxobroko.com/f=auto,w=54,h=54//images/avatar.png
  name: Uptime - Saxo_Broko
  introTitle: "Saxo_Broko's website monitor"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
